# Generated by Django 4.2.3 on 2025-03-21 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks_app', '0002_rename_transactions_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_app.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group', 'ticker')},
            },
        ),
    ]
