# Generated by Django 4.2.3 on 2025-03-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0004_usergroup_transaction_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='avg_price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_price',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='assets_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='avg_buy_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='previous_value',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=15),
        ),
    ]
