# Generated by Django 4.2.3 on 2025-03-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0005_remove_portfolio_avg_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
