# Generated by Django 4.2.3 on 2025-03-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0008_appuser_stockdata_alter_transaction_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='datetime',
            field=models.BigIntegerField(),
        ),
    ]
