# Generated by Django 4.2.3 on 2025-03-22 14:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0009_alter_stockdata_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=15),
        ),
    ]
